FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Scrabble

This API outlines the HTTP interface between the server and clients for the CS 3110 final project Scrabble.
        
## Game [/api/game{?gameName,playerName,key}]

### Subscribe to Game [GET]

+ Parameters
    + gameName - name of the game
    + playerName - name of the player
    + key - the API key

+ Response 200 (text/event-stream)

### Join a Game [POST]

+ Request (application/json)

            {
                "gameName": "<GAME_NAME>",
                "playerName": "<PLAYER_NAME>"
            }

+ Response 200 (application/json)

            {
                "key": "<API_KEY>",
                "game": {
                    "gameName": "<GAME_NAME>",
                    "grid": [
                        [' ', ' ', ' ', ' ', 'a', 't', ..., ' '],
                        [...],
                        [...],
                        ...
                    ],
                    "players": [
                        {
                            "playerName": "<PLAYER_NAME>",
                            "tiles": ['a','b','z',...,'t'],
                            "score": 0,
                            "order": 1,
                            "ai": false
                        },
                        ...
                    ],
                    "remainingTiles": ['a','w',...,'f'],
                    "turn": 0
                }
            }
            
### Create a Game [PUT]

+ Request (application/json)

            {
                "gameName": "<GAME_NAME>",
                "playerName": "<PLAYER_NAME>"
            }

+ Response 200 (application/json)

            {
                "key": "<API_KEY>",
                "game": {
                    "gameName": "<GAME_NAME>",
                    "grid": [
                        [' ', ' ', ' ', ' ', 'a', 't', ..., ' '],
                        [...],
                        [...],
                        ...
                    ],
                    "players": [
                        {
                            "player_name": "<PLAYER_NAME>",
                            "tiles": ['a','b','z',...,'t'],
                            "score": 0,
                            "order": 1,
                            "ai": false
                        },
                        ...
                    ],
                    "remainingTiles": ['a','w',...,'f'],
                    "turn": 0
                }
            }

### Leave Game [DELETE]

+ Request (application/json)

            {
                "key": "<API_KEY>",
                "playerName": "<PLAYER_NAME>",
                "gameName": "<GAME_NAME>"
            }
            
+ Response 200

## Move [/api/move]

### Execute Move [POST]

+ Request (application/json)

            {
                "key": "<API_KEY>",
                "gameName": "<GAME_NAME>",
                "move": {
                    "playerName": "<PLAYER_NAME>",
                    "tilesPlaced": [
                        {
                            "character": 'a',
                            "row": 0,
                            "col": 12
                        },
                        {
                            "character": 't',
                            "row": 0,
                            "col": 13
                        },
                    ],
                    "swappedTiles": []
                }
            }

+ Response 200

## Messaging [/api/messaging{?gameName,playerName,key}]

### Subscribe to Messages [GET]

+ Parameters
    + gameName - name of the game
    + playerName - name of the player
    + key - the API key

+ Response 200 (text/event-stream)

### Send Message [POST]

+ Request (application/json)

            {
                "key": "<API_KEY>",
                "playerName": "<PLAYER_NAME>",
                "gameName": "<GAME_NAME>",
                "msg": "<MESSAGE>"
            }
            
+ Response 200